version: '3.3'

services:
  db:
    image: mysql:5.7
    command: --explicit_defaults_for_timestamp
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rvf
      MYSQL_DATABASE: rvf-wordpress
      MYSQL_USER: user
      MYSQL_PASSWORD: rvf

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  wordpress:
    depends_on:
      - db
    build:
      context: .
      dockerfile: ./Dockerfile-wordpress
    ports:
      - 8000:80
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: user
      WORDPRESS_DB_PASSWORD: rvf
      WORDPRESS_DB_NAME: rvf-wordpress
      WORDPRESS_DEBUG: 1
volumes:
  db_data: {}